apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: nodejs-tsznxpam
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/tsscui/nodejs-tsznxpam:79ecee093407ebd6cd4f0d1bfd15cc298a1ce147@sha256:5781da57bd15f5ea5481ee639381adacf388b2f75ab65b4ee7850ca4716118bf
          name: container-image
